name: Build & Push image to ACR

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - "Dockerfile"
      - "requirements.txt"
      - ".github/workflows/build-push-acr.yml"

env:
  ACR_LOGIN_SERVER: lakmoosacr.azurecr.io
  IMAGE_NAME: aks-demo-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tag (short SHA)
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Log in to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & push (SHA tag + latest)
        run: |
          set -euo pipefail
          TAG="${{ steps.vars.outputs.TAG }}"
          echo "Using TAG=$TAG"

          docker build \
            -t "${ACR_LOGIN_SERVER}/${IMAGE_NAME}:${TAG}" \
            -t "${ACR_LOGIN_SERVER}/${IMAGE_NAME}:latest" \
            .

          docker push "${ACR_LOGIN_SERVER}/${IMAGE_NAME}:${TAG}"
          docker push "${ACR_LOGIN_SERVER}/${IMAGE_NAME}:latest"

      - name: Print tag
        run: echo "Pushed ${ACR_LOGIN_SERVER}/${IMAGE_NAME}:${{ steps.vars.outputs.TAG }} and :latest"
